baseURL: "https://mfaani.com/"
languageCode: en-us
title: TIL with Mohammad
theme: paperMod
googleAnalytics: G-Z3VBFH9DKH
env: production
uuu: "${URL}"
ddd: "${DOMAIN}"

params:
  ShowReadingTime: true
  ShowShareButtons: true
  # ShowBreadCrumbs: true // to show parent pages of a subpage
  ShowCodeCopyButtons: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: âœï¸ Blog
          url: archives/
          weight: 5
        - name: ğŸ› ï¸ Devtools 
          url: posts/devtools
          weight: 15
        - name: ğŸ“ iOS interviewing 
          url: posts/interviewing
          weight: 20
        - name: ğŸ” Search
          url: search/
          weight: 25
        - name: ğŸ·ï¸ Tags
          url: tags/
          weight: 30
        - name: ğŸ‘¨ğŸ¼â€ğŸ’» About
          url: about/
          weight: 35
  # fa:
  #     languagedirection: rtl
  #     weight: 3
  #     title: PaperMod RTL
  #     homeInfoParams:
  #         Title: "Hi there \U0001F44B"
  #         Content: Welcome to RTL layout
  #     menu:
  #         main:
  #             - name: Tags
  #               url: tags
  #               weight: 10

## neither BlackFriday nor Goldmark made any difference in the syntax highlight. Removing them for now

# not sure what this privacy does, but just adding it for now
privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

# not sure what this services does, but just adding it for now
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

  # needed to ensure different manifestations of the site work. 
outputs:
  home:
  # To create webpages. 
    - HTML
  # To create RSS Feed
    - RSS
  # To create an index.json so search works on the site
    - JSON
